name: Build Astro site & print resume PDF

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install modules (rollup)
        run: npm ci
      - name: Install dependencies (puppeteer)
        run: npm install
      - name: Startup Astro server in background
        run: docker compose up -d
      - name: Create PDF 
        run: node scripts/pdf.cjs
      - name: Cleanup
        run: docker compose down
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: example.pdf
