name: Build Astro site & print resume PDF

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #ghcr.io/puppeteer/puppeteer:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install modules
        run: npm ci
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: tree
        run: ls -l dist/
      - name: Startup Astro server in background
        run: docker compose up -d
      - name: View Ports
        run: docker ps
      - name: Create PDF 
        run: node scripts/pdf.cjs
      - name: Cleanup
        run: docker compose down
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: example.pdf
