name: Build website export resume as PDF

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Record SHA to inject onto resume output
        run: echo git rev-parse --short
        #git_hash=$(git rev-parse --short "$GITHUB_SHA")
      - name: Install dependencies for PDF generation (puppeteer)
        run: npm i puppeteer
      - name: Startup container (httpd serving Astro's built files) in background
        run: docker compose up -d
      - name: Create PDF by printing resume page
        run: npm run pdf
      - name: Cleanup
        run: docker compose down
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: example.pdf
