name: Spell Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hunspell
        run: |
          sudo apt-get update
          sudo apt-get install hunspell
          sudo apt-get install hunspell-en-us
      - name: Check hunspell dictionaries
        run: hunspell -D
      - name: Print wd
        run: ls -l 
      - name: Hunspell sanity check
        run: echo frqy refries | hunspell -a -d en_US
      - name: Spell Check resume.yml
        run: cat -n ./src/data/resume.yml | hunspell -a -d en_US
      # - name: Spell Check resume.yml
      #   run: |
      #     misspelled_words=$(hunspell ./src/data/resume.yml | grep -v '^*')
      #     if [ -n "$misspelled_words" ]; then
      #       echo "Found misspellings:"
      #       echo "$misspelled_words"
      #       exit 1
      #     fi