name: Spell Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hunspell
        run: |
          sudo apt-get update
          sudo apt-get -y install hunspell
          sudo apt-get -y install hunspell-en-us
      ### HUNSPELL Sanity Checks
      # - name: Check hunspell dictionaries
      #   run: hunspell -D
      # - name: Hunspell sanity check
      #   run: echo frqy refries | hunspell -a -d en_US
      ### HUNSPELL Custom Dictionary
      # Techincal resumes likely won't match very well to the english language...
      # A custom dictionary is stored in this repo so this jargon is not reported as 
      # misspellings. Dictionary can be found at .github/workflows/data/custom-dict
      - name: Run Spell Check on Resume
        run: |
          cat -n ./src/data/resume.yml | 
            hunspell -a -d en_US -p custom-dict.dic | # Run spell check
            grep -v -E '^\*|^@' | # Extract only misspellings from output
            grep -v '^$' | # Remove blank lines
            sort -u > hunspell_output.txt
      - name: Check for misspellings
        run: |          
          if [[ -s hunspell_output.txt ]]; then
            # Write github error annotation to show on job
            echo "::error file=resume.yml,title=misspellings-found::One or more misspellings found in resume.yml!"
            echo "::warning title=custom-dictionary::Do you need to update the custom dictionary found at .github/workflows/data/custom-dict?"          
            exit 0
          else
            # Write github annotation to show on job and exit
            echo "::notice::No misspellings found in ./src/data/resume.yml!"
            echo ":white_check_mark: Spell check passed!" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Format misspellings as markdown table
        run: |
          echo "# Spell Check Results
            | Misspelling | Near Misses |
            |---|---|" > summary_table.md

          while IFS= read -r line; do
            # Extract the first word
            first_word=$(echo "$line" | cut -d' ' -f2) 

            # Extract the suggestions (if any)
            suggestions=$(echo "$line" | cut -d':' -f2 | sed 's/^ //') 

            # Append each row onto table template
            echo "$first_word|$suggestions" >> summary_table.md
          done < hunspell_output.txt
      - name: Write table as GitHub Action job summary
        run: |
          cat summary_table.md >> $GITHUB_STEP_SUMMARY
          exit 1
